[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "wtbc_daemon"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
serde_json = "1.0.95"
shared = {path = "../shared"}
